theme: slate
title: Logs
description: Logs is a beautifully customizable and private digital pocketbook designed for minimal cognitive load. Its core experience centers around an intuitive daily view, showing only today's entries by default to keep you focused. Key features include expressive "Stamps" for one-tap visual categorization, extensive personalization of themes and tools, and complete local privacy – your data stays securely on your device unless you choose to back it up. It's a calm space to capture thoughts, moments, and ideas your way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# App Store URL
app_store_url: "https://apps.apple.com/app/your-app-id"

# Features
features:
  - title: "Feature 1"
    description: "Description of your first key feature."
  - title: "Feature 2"
    description: "Description of your second key feature."
  - title: "Feature 3"
    description: "Description of your third key feature."

# Screenshots
screenshots:
  - image: "screenshot1.png"
    alt: "App Screenshot 1"
  - image: "screenshot2.png"
    alt: "App Screenshot 2"
  - image: "screenshot3.png"
    alt: "App Screenshot 3" 